import Image from 'next/image'
import { ArrowRight, Check } from 'lucide-react'
import { Link } from '@/i18n/navigation'
import { Container } from '@/components/common/Container'
import { CleaningServiceCards } from '@/components/services/CleaningServiceCards'
import { ContactCTA } from '@/components/home/ContactCTA'
import { cleaningBasePath, cleaningContent, type CleaningService } from '@/data/cleaningServices'
import { routes } from '@/data/routes'
import { FlushingProcess } from '@/components/services/FlushingProcess'
import { HrsgDetails } from '@/components/services/HrsgDetails'
import { TankFieldGallery } from '@/components/services/TankFieldGallery'
import { CleaningMobilization } from '@/components/services/CleaningMobilization'

export function CleaningServicePage({ locale, service }: { locale: string; service?: CleaningService }) {
  const tr = locale === 'tr'
  const isFlushing = service?.slug === 'on-temizlik-flushing'
  const isHrsg = service?.slug === 'hrsg-kimyasal-temizligi'
  const isCondenser = service?.slug === 'esanjor-kondenser-kimyasal-temizligi'
  const content = service ? cleaningContent(service, locale) : undefined
  const title = content?.title ?? (tr ? 'Endüstriyel Kimyasal Temizlik' : 'Industrial Chemical Cleaning')
  const intro = content?.description ?? (tr ? 'Enerji ve proses tesislerinde HRSG, buhar kazanı, tank ve boru hatları için projeye özel kimyasal temizlik uygulamaları gerçekleştiriyoruz. Soğutma kuleleri, kondenserler ve eşanjörlerde ekipman temizliği sunuyor; uygulamayı kendi yapan firmalara kimyasal ürün tedariği ve teknik destek sağlıyoruz.' : 'We carry out project-specific chemical cleaning for HRSG systems, steam boilers, tanks and piping at energy and process facilities. We also clean cooling towers, condensers and heat exchangers and supply chemicals and technical support to businesses performing their own cleaning.')
  const scope = content?.scope ?? (tr ? ['Müşteri/EPC/OEM prosedürü veya onaya sunulan projeye özel temizlik planı.', 'Kendi temizlik ekipmanlarımız ve sirkülasyon pompalarımızla saha uygulaması.', 'Sistem malzemesi ve birikinti türüne uygun ürün seçimi ve proses takibi.', 'Proje gerekliliklerine göre flushing, durulama, nötralizasyon ve pasivasyon.'] : ['Customer, EPC or OEM procedures, or project-specific cleaning plans submitted for approval.', 'Field execution with our own cleaning equipment and circulation pumps.', 'Product selection and process monitoring suited to materials and deposits.', 'Flushing, rinsing, neutralization and passivation according to project requirements.'])
  const preparation = content?.preparation ?? (tr ? ['Tesis konumu, sistem ve ekipman türü', 'Malzeme bilgileri, P&ID ve devre hacmi', 'Birikinti örnekleri, fotoğraflar veya analizler', 'Uygulama takvimi ve mevcut prosedürler'] : ['Site location and equipment type', 'Materials, P&IDs and circuit volume', 'Deposit samples, photographs or analyses', 'Schedule and existing procedures'])
  const steps = tr ? ['Teknik inceleme', 'Prosedür ve ekipman planı', 'Kontrollü saha uygulaması', 'Durulama ve son kontroller'] : ['Technical review', 'Procedure and equipment planning', 'Controlled field execution', 'Rinsing and final checks']
  return <>
    <section className="bg-navy pb-12 pt-28 sm:pt-32"><Container><nav aria-label={tr ? 'Sayfa yolu' : 'Breadcrumb'} className="mb-7 flex flex-wrap gap-2 text-xs text-white/70"><Link href={routes.home}>{tr ? 'Ana Sayfa' : 'Home'}</Link><span>/</span><Link href={routes.services}>{tr ? 'Hizmetlerimiz' : 'Services'}</Link>{service && <><span>/</span><Link href={cleaningBasePath}>{tr ? 'Endüstriyel Kimyasal Temizlik' : 'Industrial Chemical Cleaning'}</Link></>}<span>/</span><span className="text-white">{title}</span></nav><div className="grid items-center gap-8 lg:grid-cols-[1.2fr_1fr]"><div><p className="text-xs font-bold uppercase tracking-widest text-cyan">{tr ? 'Projeye özel saha uygulaması' : 'Project-specific field services'}</p><h1 className="mt-4 text-3xl font-bold leading-tight text-white sm:text-4xl lg:text-5xl">{title}</h1>{content && <p className="mt-4 text-base leading-relaxed text-white/75">{content.summary}</p>}<Link href={routes.contact} className="mt-6 inline-flex items-center gap-2 rounded-xl gradient-accent px-5 py-3 font-semibold text-white">{tr ? 'Projenizi Değerlendirelim' : 'Discuss Your Project'}<ArrowRight className="h-4 w-4" /></Link></div><div className="relative aspect-[16/10] overflow-hidden rounded-2xl"><Image src={isFlushing ? '/images/services/flushing-pipe-interior.jpg' : service?.image ?? '/images/services/ahal-chemical-cleaning.jpeg'} alt={title} fill sizes="(min-width: 1024px) 45vw, 100vw" className="object-cover" priority /></div></div></Container></section>
    <section className="bg-[#eef5f8] py-14"><Container><div className="grid gap-8 lg:grid-cols-[1.5fr_1fr]"><div><h2 className="text-2xl font-bold text-navy">{tr ? 'Teknik Yaklaşımımız' : 'Our Technical Approach'}</h2><p className="mt-4 text-base leading-relaxed text-navy/70">{intro}</p>{content && <ul className="mt-5 flex flex-wrap gap-2">{content.applications.map(item => <li key={item} className="rounded-full border border-cyan/20 bg-white px-3 py-1.5 text-xs font-semibold text-brand-blue">{item}</li>)}</ul>}<h2 className="mb-4 mt-8 text-2xl font-bold text-navy">{tr ? 'Hizmet Kapsamımız' : 'Service Scope'}</h2><ul className="space-y-3">{scope.map(item => <li key={item} className="flex gap-3 rounded-xl bg-white p-4 text-sm leading-relaxed text-navy/75"><Check className="mt-1 h-4 w-4 shrink-0 text-cyan" />{item}</li>)}</ul></div><aside className="self-start rounded-2xl border border-navy/10 bg-white p-6"><h2 className="text-xl font-bold text-navy">{tr ? 'Teklif İçin Hangi Bilgiler Gerekli?' : 'What Information Helps Us Prepare a Quote?'}</h2><p className="mt-3 text-sm leading-relaxed text-navy/65">{tr ? 'Mevcut bilgilerinizi paylaşın; eksik teknik detayları birlikte netleştirelim.' : 'Share the information available to you; we can clarify remaining technical details together.'}</p><ul className="mt-5 space-y-3">{preparation.map(item => <li key={item} className="flex gap-2 text-sm text-navy/75"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan" />{item}</li>)}</ul><Link href={routes.contact} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-brand-blue">{tr ? 'Teknik Değerlendirme Talep Et' : 'Request Technical Assessment'}<ArrowRight className="h-4 w-4" /></Link></aside></div></Container></section>
    {isFlushing && <FlushingProcess locale={locale} />}
    {(!service || isHrsg) && <CleaningMobilization locale={locale} compact={isHrsg} />}
    {isHrsg && <HrsgDetails locale={locale} />}
    {service?.slug === 'tank-boru-hatti-kimyasal-temizligi' && <TankFieldGallery locale={locale} />}
    <section className="py-14"><Container>{!isFlushing && !isHrsg && <h2 className="mb-7 text-2xl font-bold text-navy">{tr ? 'Uygulama Sürecimiz' : 'Our Application Process'}</h2>}{!isFlushing && !isHrsg && <ol className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{steps.map((step, i) => <li key={step} className="rounded-xl border border-navy/10 p-5"><span className="text-sm font-bold text-cyan">0{i + 1}</span><h3 className="mt-3 font-bold text-navy">{step}</h3></li>)}</ol>}<p className="mt-4 text-sm leading-relaxed text-navy/60">{tr ? 'Kimyasal türü, konsantrasyon, sıcaklık, süre ve kabul kriterleri her proje için sistem koşullarına ve onaylı prosedüre göre belirlenir.' : 'Chemical type, concentration, temperature, duration and acceptance criteria are defined for each project according to system conditions and the approved procedure.'}</p>{content && <div className="mt-8 rounded-2xl bg-navy p-6"><h2 className="text-xl font-bold text-white">{tr ? 'İlgili Saha Deneyimimiz' : 'Related Field Experience'}</h2><p className="mt-3 text-sm leading-relaxed text-white/75">{content.reference}</p>{isCondenser && <div className="mt-5 grid gap-3 sm:grid-cols-2">{[{ id: 'apikoglu-sogutma-kulesi-kondenser', name: tr ? 'Apikoğlu Kondenser Temizliği' : 'Apikoğlu Condenser Cleaning' }, { id: 'ss-agakoy-tarimsal-kalkinma-kooperatifi', name: tr ? 'S.S. Ağaköy Evaporatif Kondenser Temizliği' : 'S.S. Ağaköy Evaporative Condenser Cleaning' }].map(project => <Link key={project.id} href={routes.projects + '#' + project.id} className="rounded-xl border border-white/15 bg-white/5 p-4 transition hover:bg-white/10"><h3 className="font-semibold text-white">{project.name}</h3><span className="mt-2 inline-flex items-center gap-2 text-sm font-semibold text-cyan">{tr ? 'Projeyi ve Uygulama Videosunu İncele' : 'View Project and Application Video'}<ArrowRight className="h-4 w-4" /></span></Link>)}</div>}<Link href={routes.projects} className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-cyan">{tr ? 'Proje Kayıtlarımızı İnceleyin' : 'Explore Our Project Records'}<ArrowRight className="h-4 w-4" /></Link></div>}</Container></section>
    <section className="bg-[#eef5f8] py-14"><Container><h2 className="mb-7 text-2xl font-bold text-navy">{tr ? (service ? 'Diğer Kimyasal Temizlik Hizmetlerimiz' : 'Sisteminize Uygun Hizmeti İnceleyin') : (service ? 'Other Chemical Cleaning Services' : 'Explore Services for Your System')}</h2><CleaningServiceCards locale={locale} excludeSlug={service?.slug} /></Container></section>
    <ContactCTA />
  </>
}
